# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4fde23e3919327ad5f72fb5a75fd2a2708d93c52b8a20e27c786657627426feb8cc5cccc35478cce4e349a65e60fefb04634d1192edda5e175b21d4c6b345d

test:
  secret_key_base: 2b6923a079a6e0815b54989bbfe63818cd797d7a7f2f54d0812e56119085810229d0c0a4ef333819adb26fc3b24e9898350d961e2334f9206bd336e9c711f0a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
